import { test, expect } from '@playwright/test';
test('real app: independently compress, inspect tokens, export, and capture desktop', async ({ page }, testInfo) => {
    const pageErrors: string[] = [];
    page.on('pageerror', e => pageErrors.push(e.message));
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.goto('/');
    await page.getByRole('button', { name: 'Research', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Original prompt', exact: true })).toBeVisible();
    await page.getByLabel('Load example').selectOption('redundancy');
    await page.getByRole('button', { name: 'Analyze prompt', exact: false }).click();
    await expect(page.locator('.statusbar')).toContainText('analyzed');
    await page.locator('.method-card').filter({ hasText: 'Redundancy' }).click();
    await expect(page.locator('.statusbar')).toContainText('complete');
    await expect(page.locator('.history tbody tr')).toHaveCount(1);
    await page.getByRole('tab', { name: 'Side by side' }).click();
    const pre = page.locator('.side-grid pre');
    const original = await pre.nth(0).innerText(), compressed = await pre.nth(1).innerText();
    expect(compressed.length).toBeLessThan(original.length);
    expect(compressed).toContain('Do NOT promise automatic plant identification.');
    await page.getByRole('tab', { name: 'Original tokens' }).click();
    await expect(page.locator('.token-inspector')).toBeVisible();
    const downloadPromise = page.waitForEvent('download');
    await page.getByRole('button', { name: 'Export JSON', exact: true }).click();
    expect((await downloadPromise).suggestedFilename()).toBe('tokenlab-experiments.json');
    await page.getByRole('tab', { name: 'Visual diff' }).click();
    await page.screenshot({ path: testInfo.outputPath('tokenlab-desktop.png'), fullPage: true });
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: testInfo.outputPath('tokenlab-desktop-top.png') });
    expect(pageErrors).toEqual([]);
});
test('JSON is preserved, and changing input isolates the notebook', async ({ page }) => {
    await page.goto('/');
    await page.getByRole('button', { name: 'Research', exact: true }).click();
    await page.getByLabel('Load example').selectOption('json');
    const original = await page.getByLabel('Original prompt', { exact: true }).inputValue();
    await page.locator('.method-card').filter({ hasText: 'Importance + math' }).click();
    await expect(page.locator('.statusbar')).toContainText('complete');
    await page.getByRole('tab', { name: 'Side by side' }).click();
    expect(await page.locator('.side-grid pre').nth(1).innerText()).toBe(original);
    await page.getByLabel('Load example').selectOption('negation');
    await expect(page.locator('.history tbody tr')).toHaveCount(0);
    await page.locator('.method-card').filter({ hasText: 'Function-word' }).click();
    await expect(page.locator('.statusbar')).toContainText('complete');
    await page.getByRole('tab', { name: 'Side by side' }).click();
    await expect(page.locator('.side-grid pre').nth(1)).toContainText('Do NOT delete the database.');
});
test('mobile has no page-wide overflow and Gemini is opt-in', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto('/');
    await page.getByRole('button', { name: 'Research', exact: true }).click();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true);
    await page.locator('.arena summary').click();
    await expect(page.getByRole('button', { name: 'Check local gateway', exact: true })).toBeDisabled();
    await expect(page.getByRole('button', { name: /Compare original vs compressed/ })).toBeDisabled();
});
