import type { Run } from '../engine/types.js';
import { chunkCounts, compareDecisions, runLabel, STUDY_TITLES, studyObservations, targetTokens } from '../engine/studies.js';
import { TransformChart } from './Charts.js';
import { focusLabel } from './TaskFocusControls.js';

const percent = (n: number | null) => n === null ? '—' : `${(n * 100).toFixed(1)}%`;
export function StudyResults({ runs, selected, onSelect, changed }: { runs: Run[]; selected?: string; onSelect: (id: string) => void; changed: boolean }) {
    const first = runs[0];
    if (!first?.study) return null;
    if (runs.length !== first.study.total) return <p className="notice">Only {runs.length}/{first.study.total} runs from this study remain in the 100-run history. Run a new study for a complete comparison.</p>;
    const ladder = first.study.kind === 'ladder';
    const sigmoid = runs.find(r => r.settings.transform === 'sigmoid'), softmax = runs.find(r => r.settings.transform === 'softmax');
    const pair = !ladder && sigmoid && softmax ? compareDecisions(sigmoid, softmax) : null;
    const inspect = (id: string) => {
        onSelect(id);
        requestAnimationFrame(() => {
            const heading = document.getElementById('result-heading');
            heading?.focus({ preventScroll: true }); heading?.scrollIntoView({ block: 'start' });
        });
    };
    return <section className="panel study-results" aria-labelledby="study-heading">
        <div className="section-heading"><div><span className="eyebrow">CONTROLLED EXPERIMENT / {runs.length} INDEPENDENT RUNS</span><h2 id="study-heading" tabIndex={-1}>{STUDY_TITLES[first.study.kind]}</h2></div><span className="badge">ONLY {ladder ? 'BUDGET' : 'TRANSFORM'} CHANGES</span></div>
        <p className="study-question">{ladder ? 'How does increasingly aggressive compression change what survives?' : pair && runs.length === 2 ? 'What changes when scores are shaped independently versus shared across competing chunks?' : 'Can monotonic shaping change which information fits inside a token budget?'}</p>
        <p className="fineprint">Same original · {first.metrics.originalTokens} tokens · {first.settings.encoding} · {focusLabel(first.taskFocus.policy)} task focus · same weights, raw features and protection. {ladder ? `Fixed ${first.settings.transform} transform.` : `Fixed target: ${targetTokens(first)} tokens (${percent(first.settings.budget)} retained).`} Weighted importance uses {first.settings.useEmbeddings ? 'local embedding' : 'lexical'} relevance.</p>
        {changed && <p className="notice">Controls changed since this study. These are the recorded results; run a new study to compare the new settings.</p>}
        <div className="study-process" aria-label="Selection process">Importance <span>→</span> Shaping <span>→</span> Cutoff / value per token <span>→</span> Budget <span>→</span> What survives</div>
        {ladder && <div className="ladder" aria-label="Independent budget levels"><div className="ladder-original"><small>ORIGINAL</small><strong>{first.metrics.originalTokens} tokens</strong><span>Every level starts here.</span></div>{runs.map(r => <button key={r.id} className={r.id === selected ? 'selected' : ''} onClick={() => inspect(r.id)} aria-label={`Inspect ${runLabel(r)}`}><strong>{Math.round(r.settings.budget * 100)}% target</strong><span>{targetTokens(r)} target → {r.metrics.compressedTokens} actual tokens</span><span className="ladder-meter"><i style={{ width: `${Math.min(100, (r.metrics.rate ?? 0) * 100)}%` }}/><b style={{ left: `${r.settings.budget * 100}%` }}/></span><span>{percent(r.metrics.rate)} actually retained</span><small>{r.budgetMet ? 'Budget met' : 'Budget unmet · constraints preserved'} · Inspect text ↗</small></button>)}</div>}
        <div className="table-scroll study-table" tabIndex={0} role="region" aria-label="Study comparison table, scroll horizontally for all metrics"><table><caption>{ladder ? 'Budget ladder' : 'Transform comparison'} · actual full-string BPE counts</caption><thead><tr><th>{ladder ? 'Budget' : 'Transform'}</th><th>Original</th><th>Target</th><th>Actual tokens</th><th>Saved</th><th>Savings</th><th>Factor</th><th>Protection</th><th>Cosine</th><th>Kept / removed</th><th>Budget</th></tr></thead><tbody>{runs.map(r => <tr key={r.id} className={r.id === selected ? 'selected' : ''}><th scope="row"><button className="table-link" onClick={() => inspect(r.id)} aria-label={`Inspect ${runLabel(r)} result`}>{runLabel(r)} ↗</button></th><td>{r.metrics.originalTokens}</td><td>{targetTokens(r)}</td><td><strong>{r.metrics.compressedTokens}</strong></td><td>{r.metrics.savedTokens}</td><td>{r.metrics.savingsPercent.toFixed(1)}%</td><td>{r.metrics.factor === null ? '—' : `${r.metrics.factor.toFixed(2)}×`}</td><td>{percent(r.metrics.protectionRate)}</td><td>{r.similarity?.cosine.toFixed(4) ?? '—'}</td><td>{chunkCounts(r).kept} / {chunkCounts(r).removed}</td><td>{r.budgetMet ? 'Met' : 'Unmet'}</td></tr>)}</tbody></table></div>
        <p className="fineprint">Protected chunks bypass cutoff and can exceed the budget. Protection means detected exact occurrences, not complete meaning preservation. Counts include whitespace chunks. “—” means missing; no semantic values are inferred.</p>
        <div className="study-learning"><span className="eyebrow">WHAT ARE WE LEARNING?</span><ul>{studyObservations(runs).map(text => <li key={text}>{text}</li>)}</ul></div>
        {pair && <details className="pair-comparison" open={runs.length === 2}><summary>Sigmoid vs Softmax · same chunks, different math</summary><div className="pair-concepts"><div><h3>Sigmoid · each score</h3><code>1 / (1 + exp(−k(x − t)))</code><p>Each score is shaped independently around center t = {sigmoid!.settings.center}. Steepness k = {sigmoid!.settings.steepness} separates scores below and above that center.</p></div><div><h3>Softmax · the whole set</h3><code>exp(xᵢ/T) / Σ exp(xⱼ/T)</code><p>Relative shares across all {pair.length} chunks, including protected and whitespace chunks. T = {softmax!.settings.temperature}; lower T concentrates, higher T flattens. Shares sum to one.</p></div></div>
            <div className="decision-key">{(['Same decision', 'Sigmoid only', 'Softmax only', 'Removed by both'] as const).map(label => <span key={label} className={`decision-chip ${label.toLowerCase().replaceAll(' ', '-')}`}>{label === 'Same decision' ? 'Same decision · both kept' : label}: <b>{pair.filter(row => row.agreement === label).length}</b></span>)}</div>
            <p className="fineprint">Sigmoid cutoff {sigmoid!.settings.cutoff.toFixed(3)}; Softmax share cutoff {(softmax!.settings.cutoff / Math.max(1, pair.length)).toPrecision(4)} = slider ÷ chunk count. Scores have different scales; neither is a calibrated probability that a chunk is needed.</p>
            <details className="chunk-comparison"><summary>Inspect all {pair.length} chunk decisions</summary><div className="table-scroll" tabIndex={0} role="region" aria-label="Paired chunk decisions, scroll horizontally"><table><thead><tr><th>Original chunk</th><th>Raw</th><th>Sigmoid</th><th>Softmax share</th><th>Sigmoid decision</th><th>Softmax decision</th><th>Comparison</th></tr></thead><tbody>{pair.map(({ sigmoid: a, softmax: b, agreement }) => <tr key={a.index}><th scope="row" className="chunk-text"><small>#{a.index + 1}{a.hardProtected && ' · PROTECTED'}</small><span>{a.text.trim() ? a.text : '[whitespace]'}</span></th><td>{a.originalScore.toFixed(4)}</td><td>{a.transformedScore.toFixed(4)}</td><td>{b.transformedScore.toFixed(4)}</td><td title={a.reason}>{a.kept ? 'Retained' : 'Removed'}</td><td title={b.reason}>{b.kept ? 'Retained' : 'Removed'}</td><td><span className={`decision-chip ${agreement.toLowerCase().replaceAll(' ', '-')}`}>{agreement}</span></td></tr>)}</tbody></table></div></details>
        </details>}
        <details className="study-curves"><summary>How the math shapes importance</summary><TransformChart settings={sigmoid?.settings ?? first.settings}/></details>
        <details className="study-record"><summary>Recorded controls and reproducibility</summary><p className="fineprint">Study {first.study.id} · {first.engineVersion} · {first.timestamp}<br/>Input SHA-256: {first.inputHash}<br/>Task-focus SHA-256: {first.taskFocus.textHash}</p><p className="fineprint">Cutoff {first.settings.cutoff}; sigmoid k {first.settings.steepness}, t {first.settings.center}; softmax T {first.settings.temperature}. Weights: {Object.entries(first.settings.weights).map(([k,v]) => `${k} ${v}`).join(' · ')}. {first.settings.protectedTerms.length} custom protected strings. Full decisions, settings, hashes and model metadata are in the experiment notebook export. Prompt text is excluded by default.</p></details>
    </section>;
}
